### ISSUE TITLE
readme - missing #include <sys/csr.h>

### ISSUE THREAD

**Issue by johndpope** [opensource-apple/dtrace#1]
I'm trying to compile dtrace to osx.
how do I find this library?

**Comment by johndpope** [comment]
@artman - I enjoyed your talk https://www.skilled.io/u/swiftsummit/swift-with-a-hundred-engineers
I noticed you mentioned you are using dtrace internally - perhaps one of your engineers could help out getting this working?

**Comment by candeladiao** [comment]
missing #include <sys/csr.h> 
change TARGET_OS_EMBEDDED to TARGET_OS_OSX then missing #include <sys/kas_info.h>

**Comment by johndpope** [comment]
Thanks
